### ISSUE TITLE
CRAN name conflict

### ISSUE THREAD

**Issue by mattfidler** [r-prof/jointprof#21]
I think this is an excellent idea/package.

I just wanted to point out there is a CRAN package with a name conflict for this package.

https://cran.r-project.org/web/packages/gProfileR/index.html

While the case is different, I'm unsure if you want to have 2 packages with the same name.

**Comment by krlmlr** [comment]
Thanks, I better should have checked with *available* before. I'm not in love with the new name, open for alternatives.
