### ISSUE TITLE
Decide what to do with write_flat_ds()

### ISSUE THREAD

**Issue by atheriel** [r-prof/jointprof#42]
The package currently contains a `write_flat_ds()` function (in `debug.R`) that is not exported, used anywhere else in the package, or used in any tests. In addition, this function is the sole user of the **readr** dependency, although that could probably be moved to Suggests or replaced with `utils::write.csv()`.

I think there are a few possible ways to deal with this (currently) dead code:

- Remove it.
- Use it in the test suite; or
- Move it to the **profile** package.

**Comment by krlmlr** [comment]
Let's get rid of it, we have better facilities for flattening in the new {dm} package.
